kind: pipeline
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

- name: dev-build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vertigo235/fw-build
    tags: 
        #- ${DRONE_TAG:-${DRONE_BRANCH}}
        - ${DRONE_BRANCH}
    cache_from: vertigo235/fw-build
  when:
    branch:
      exclude:
        - master
    event:
      - push
    
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vertigo235/fw-build
    tags:
      - '1'
      - '1.2'
      - '1.2.${DRONE_BUILD_NUMBER}'
    #auto_tag: true
    cache_from: vertigo235/fw-build
  when:
    branch:
      - master