kind: pipeline
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

- name: test-build
  image: docker
  commands:
    - docker build . --cache-from vertigo235/fw-build
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  when:
    branch: 
      exclude: master
    event:
      exclude: tag
    
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vertigo235/fw-build
    auto_tag: true
    cache_from: vertigo235/fw-build
  when:
    branch:
      - master

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock